# This template creates an ir-vpc in the Security Account which is used by the ir-automations solution to run forensics automation tasks.  
# © 2020 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.  
# This AWS Content is provided subject to the terms of the AWS Customer Agreement available at  
# http://aws.amazon.com/agreement or other written agreement between Customer and either
# Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

AWSTemplateFormatVersion: 2010-09-09
Description: >
  ir-vpc

  CloudFormation template to deploy and configure a VPC used for IR volume processing
  
Parameters:
  pAvailabilityZone:
    Type: "AWS::EC2::AvailabilityZone::Name"
    Description: Availability Zone to Launch EC2 instance
  pIRArtifactBucket:
    Type: String
    Description: Name of the Forensic Account S3 IR Artifacts Bucket
    AllowedPattern: "[a-zA-Z0-9-.]*"
    ConstraintDescription: bucket name must contain only lowercase letters, numbers, periods (.), and dashes (-).
  pIRVpcCidr:
    Type: String
    Description: CIDR for the IR VPC
    Default: 10.192.0.0/16
    AllowedPattern: "([0-9.\\/]*)"
    ConstraintDescription: must meet the form of an IP CIDR (e.g. 10.192.0.0/16).
  pIRVpcSubnetCidr:
    Type: String
    Description: CIDR for the IR VPC Subnet
    Default: 10.192.1.0/24
    AllowedPattern: "([0-9.\\/]*)"
    ConstraintDescription: must meet the form of an IP CIDR (e.g. 10.192.0.0/16).

Resources:
  rIRVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref pIRVpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: ir-vpc

  rIRSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref pIRVpcSubnetCidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref rIRVpc
      Tags:
        - Key: Name
          Value: ir-subnet
      AvailabilityZone: !Ref pAvailabilityZone

  rIRRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref rIRVpc
      Tags:
        - Key: Name
          Value: IR VPC Route Table
  
  rRouteTableIRSubnetAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rIRRouteTable
      SubnetId: !Ref rIRSubnet  

  rInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Securtiy Group for IR Instance
      GroupName: ir-instance-sg
      VpcId: !Ref rIRVpc
    
  rEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Securtiy Group for IR VPC Endpoints
      GroupName: ir-vpce-sg
      SecurityGroupIngress:
      - IpProtocol: 'tcp'
        FromPort: 443
        ToPort: 443
        SourceSecurityGroupId: !Ref rInstanceSecurityGroup 
      VpcId: !Ref rIRVpc

  rS3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:PutObjectAcl'
              - 's3:CreateMultipartUpload'
              - 's3:AbortMultipartUpload'
              - 's3:GetBucketLocation'
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
            Resource: !Sub "arn:${AWS::Partition}:s3:::${pIRArtifactBucket}/*"
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref rIRRouteTable
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref rIRVpc

  rSSMEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      SubnetIds:
        - !Ref rIRSubnet
      PrivateDnsEnabled: True
      SecurityGroupIds: 
        - !Ref rEndpointSecurityGroup
      VpcEndpointType: Interface
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ssm'
      VpcId: !Ref rIRVpc

  rSSMMessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      SubnetIds:
        - !Ref rIRSubnet
      PrivateDnsEnabled: True
      VpcEndpointType: Interface
      SecurityGroupIds: 
        - !Ref rEndpointSecurityGroup
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ssmmessages'
      VpcId: !Ref rIRVpc

  rEC2MessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      SubnetIds:
        - !Ref rIRSubnet
      PrivateDnsEnabled: True
      VpcEndpointType: Interface
      SecurityGroupIds: 
        - !Ref rEndpointSecurityGroup
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ec2messages'
      VpcId: !Ref rIRVpc